package com.quenazapps.bibleriddles.activity.stages

import android.app.Activity
import com.quenazapps.bibleriddles.domain.PlayerInfo.Companion.TOTAL_STAGES

private val stageActivities: List<Class<out Activity>> = listOf(
    Stage1Activity::class.java,
    Stage2Activity::class.java,
    Stage3Activity::class.java,
    Stage4Activity::class.java,
    Stage5Activity::class.java,
    Stage6Activity::class.java,
    Stage7Activity::class.java,
    Stage8Activity::class.java,
    Stage9Activity::class.java,
    Stage10Activity::class.java,
    Stage11Activity::class.java,
    Stage12Activity::class.java,
    Stage13Activity::class.java,
    Stage14Activity::class.java,
    Stage15Activity::class.java,
    Stage16Activity::class.java,
    Stage17Activity::class.java,
    Stage18Activity::class.java,
    Stage19Activity::class.java,
    Stage20Activity::class.java,
    Stage21Activity::class.java,
    Stage22Activity::class.java,
    Stage23Activity::class.java,
    Stage24Activity::class.java,
    Stage25Activity::class.java,
    Stage26Activity::class.java,
    Stage27Activity::class.java,
    Stage28Activity::class.java,
    Stage29Activity::class.java,
    Stage30Activity::class.java,
    Stage31Activity::class.java,
    Stage32Activity::class.java,
    Stage33Activity::class.java,
    Stage34Activity::class.java,
    Stage35Activity::class.java,
    Stage36Activity::class.java,
    Stage37Activity::class.java,
    Stage38Activity::class.java,
    Stage39Activity::class.java,
    Stage40Activity::class.java,
    Stage41Activity::class.java,
    Stage42Activity::class.java,
    Stage43Activity::class.java,
    Stage44Activity::class.java,
    Stage45Activity::class.java,
    Stage46Activity::class.java,
    Stage47Activity::class.java,
    Stage48Activity::class.java,
    Stage49Activity::class.java,
    Stage50Activity::class.java,
)

fun stageActivityClass(stageNumber: Int): Class<out Activity> =
    stageActivities[stageNumber.coerceIn(1, TOTAL_STAGES) - 1]
